//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFGreenBean.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Section
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Section()
        {
            this.CourseTakens = new HashSet<CourseTaken>();
            this.StudentSchedules = new HashSet<StudentSchedule>();
        }
    
        public int SectionId { get; set; }
        public string Name { get; set; }
        public Nullable<float> Units { get; set; }
        public string Day { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public string Room { get; set; }
        public string Instructor { get; set; }
        public string Term { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> StartDate { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Status { get; set; }
        public string Type { get; set; }
        public System.DateTime StartDayTime1 { get; set; }
        public System.DateTime EndDayTime1 { get; set; }
        public Nullable<System.DateTime> StartDayTime2 { get; set; }
        public Nullable<System.DateTime> EndDayTime2 { get; set; }
        public Nullable<int> CourseId { get; set; }
    
        public virtual Course Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseTaken> CourseTakens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentSchedule> StudentSchedules { get; set; }
    }
}
